#!/bin/sh

distribution=$1
dist_version=$2
package=$3
distdir=$4
release=$5

if test -z $release; then
  release="0.fc8"
fi

sed -e "s/SILC_VERSION/$dist_version/" -e "s/SILC_RELEASE/$release/" \
  srt.spec.in > srt.spec

# First configure with debug and stacktrace and run all tests
./configure --enable-debug --enable-stack-trace
make clean
make -j4
make check -j4

# Then actual configuration and making
./configure
make clean
make -j4
make check -j4

cd doc
make toolkit-ref-html
cd ..
cp ChangeLog doc/runtime/ChangeLog
